server:
  port: 8085

spring:
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/RajKhandekar/microservice-config
            default-label: main
  profiles:
    active: native             